# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fcc9d5406491d23cad5104c13cec53c2f60a911d77e0b21f936f7e150054b475e0f22779afd2be5ca94e512be4a083c15e23f3655d41ef88d740c4083a9b50e

test:
  secret_key_base: f9698703cb60d91c2cd80a127fd64adc81638b3d223ad6b7ab17bdad62a09807dcceba5af10793f3125eb8ed9ee2e44136f6188cc4609cc8fa3d58c5cb20468e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
